# Nivell 1

## Exercici 1

#### Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [1]:
import numpy as np
import random

In [2]:
def basicStat(array):
    if len(array.shape) > 1:
        print(f'Error. This array is multidimension: \n{array}\nshape: {array.shape}')
    else:
        print(f'This is your array: {array}. \nHere´s the min: {array.min()}, \nmean: {array.mean()}, \nmax: {array.max()}, \nstd: {array.std()}, \nvar: {array.var()}')

In [3]:
arr_1 = np.random.randint(0, 50, 12)
arr_2 = np.random.randint(0, 50, 12) 
arr_3 = np.random.randint(0, 50, 12).reshape(4, 3)

In [4]:
arr_3

array([[28, 25, 11],
       [26, 42, 26],
       [23, 16,  7],
       [30, 42, 33]])

In [5]:
basicStat(arr_1)

This is your array: [13 23 21 37 23 34 36 25 21 21 26 37]. 
Here´s the min: 13, 
mean: 26.416666666666668, 
max: 37, 
std: 7.454957336490189, 
var: 55.57638888888889


In [6]:
basicStat(arr_2)

This is your array: [25 46 31 42 49 22  0 45 14 17 30 47]. 
Here´s the min: 0, 
mean: 30.666666666666668, 
max: 49, 
std: 14.957346764123049, 
var: 223.72222222222226


In [7]:
basicStat(arr_3)

Error. This array is multidimension: 
[[28 25 11]
 [26 42 26]
 [23 16  7]
 [30 42 33]]
shape: (4, 3)


## Exercici 2

#### Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [8]:
def matrixGenerator(num):
    return np.random.randint(0, 100, num*num).reshape(num, num)

In [9]:
matrixGenerator(5)

array([[29, 10, 92, 80, 28],
       [92, 32, 46, 69, 64],
       [96, 98,  9, 24, 54],
       [47, 79, 66, 65, 56],
       [10, 29, 19, 31, 38]])

In [10]:
matrixGenerator(7)

array([[14, 61, 98, 87, 52, 39, 78],
       [76, 71, 71, 10, 91, 81, 97],
       [22, 99, 57, 47, 34,  4, 37],
       [45, 87, 54, 71, 46, 68, 25],
       [41, 37, 60, 24, 81, 18, 73],
       [ 9, 84, 50, 74, 82, 10, 92],
       [23, 36, 90, 70, 76, 16, 77]])

In [11]:
matrixGenerator(3)

array([[45, 78, 40],
       [ 8, 91, 96],
       [40, 45, 53]])

## Exercici 3

#### Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

In [12]:
def dosDMatrixCalc(array):
    if len(array.shape) < 2:
        print('Error. This function only accepts 2-d matrixes.')
    else:
        for row in range(len(array)):
            print(f'Total sum of row {row}: {array[row].sum()}')
        array_transp = array.transpose()
        for row in range(len(array_transp)):
            print(f'Total sum of column {row}: {array_transp[row].sum()}')

In [13]:
dosDMatrixCalc(arr_1)

Error. This function only accepts 2-d matrixes.


In [14]:
dosDMatrixCalc(arr_2)

Error. This function only accepts 2-d matrixes.


In [15]:
dosDMatrixCalc(arr_3)

Total sum of row 0: 64
Total sum of row 1: 94
Total sum of row 2: 46
Total sum of row 3: 105
Total sum of column 0: 107
Total sum of column 1: 125
Total sum of column 2: 77


In [16]:
dosDMatrixCalc(np.array([[1,2,3],[4,5,6]]))

Total sum of row 0: 6
Total sum of row 1: 15
Total sum of column 0: 5
Total sum of column 1: 7
Total sum of column 2: 9


## Exercici 4

#### Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

El coeficiente de correlacion entre valores indica cual es el nível de relación entre ellos y puede variar entre -1 y 1.  
Si es 1, son perfectamente positiva.  
Si es -1, su relación es perfectamente negativa.  
SI es 0, no tienen relación.

In [19]:
import pandas as pd

In [40]:
def coefCorr(array):
    coef_corr = []
    
    cov_n = 0
    sigma_col_n = 0
    sigma_col_n_1 = 0
    
    for n in range(0, array.shape[1]):
        for e in range(0, array.shape[1]):
            for f, g in zip(array[::,n], array[::,e]):
                
                cov_n += (f-np.mean(array[::,n]))*(g-np.mean(array[::,e]))
        
            for w, j in zip(array[::,n], array[::,e]):
                sigma_col_n += (w-np.mean(array[::,n]))**2
                sigma_col_n_1 += (j-np.mean(array[::,e]))**2
        
            std_coln_coln1 = (np.sqrt(sigma_col_n))*(np.sqrt(sigma_col_n_1))
        
            coef_corr_coln_coln1 = cov_n/std_coln_coln1
        
            coef_corr.append(np.round(coef_corr_coln_coln1, decimals=4))
        
            cov_n = 0
            sigma_col_n = 0
            sigma_col_n_1 = 0
    
    return np.array(coef_corr).reshape(array.shape[1], array.shape[1])

#### Para probar la función voy usar 4 arrays distintos y comparar su resultado con los resultados del modulo pd.corr() en cada uno de ellos para chequear si los valores son iguales.

**Prueba 1**

In [39]:
pd.DataFrame(arr_3).corr()

0         1         2
0  1.000000  0.657509  0.683778
1  0.657509  1.000000  0.961548
2  0.683778  0.961548  1.000000

In [44]:
coefCorr(arr_3)

array([[1.    , 0.6575, 0.6838],
       [0.6575, 1.    , 0.9615],
       [0.6838, 0.9615, 1.    ]])

**Prueba 2**

In [22]:
dados_pax = np.array([[55,163,65], [78,182,34], [49,150,87], [87,190,29]])

In [54]:
pd.DataFrame(dados_pax, columns=['peso', 'altura', 'idade']).corr()

peso    altura     idade
peso    1.000000  0.986839 -0.972603
altura  0.986839  1.000000 -0.993790
idade  -0.972603 -0.993790  1.000000

In [55]:
coefCorr(dados_pax)

array([[ 1.    ,  0.9868, -0.9726],
       [ 0.9868,  1.    , -0.9938],
       [-0.9726, -0.9938,  1.    ]])

**Prueba 3**

In [46]:
posib_lluvia_paraguas = np.array([[1, 0.8], [0.7, 0.65], [0.5, 0.2], [0.2, 0]])

In [53]:
pd.DataFrame(posib_lluvia_paraguas, columns=['posibilidad lluvia', 'personas_con_paraguas']).corr()

posibilidad lluvia  personas_con_paraguas
posibilidad lluvia               1.000000               0.963744
personas_con_paraguas            0.963744               1.000000

In [48]:
coefCorr(posib_lluvia_paraguas)

array([[1.    , 0.9637],
       [0.9637, 1.    ]])

**Prueba 4**

In [49]:
dados_coche = np.array([[150, 15, 2, 400],[350, 5, 4, 300],[80, 20, 4, 600],[110, 13, 4, 700]])

In [51]:
pd.DataFrame(dados_coche, columns=['potencia','km/l','# portas','autonomia']).corr()

potencia      km/l  # portas  autonomia
potencia   1.000000 -0.927065  0.123195  -0.824717
km/l      -0.927065  1.000000 -0.187016   0.614598
# portas   0.123195 -0.187016  1.000000   0.365148
autonomia -0.824717  0.614598  0.365148   1.000000

In [52]:
coefCorr(dados_coche)

array([[ 1.    , -0.9271,  0.1232, -0.8247],
       [-0.9271,  1.    , -0.187 ,  0.6146],
       [ 0.1232, -0.187 ,  1.    ,  0.3651],
       [-0.8247,  0.6146,  0.3651,  1.    ]])